FROM python:3.10

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt /app


RUN pip3 install --upgrade setuptools \
    && pip3 install --upgrade pip \
    && pip install -r requirements.txt

COPY . /app

#CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "9000", "--reload"]